In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("data/201704health.xlsx")
df.head(6)

           日付     歩数  摂取カロリー
0  2017-04-01   5439    2500
1  2017-04-02   2510    2300
2  2017-04-03  10238    1950
3  2017-04-04   8209    1850
4  2017-04-05   9434    1930
5  2017-04-06   7593    1800

In [3]:
df["歩数"] >= 10000

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19     True
20     True
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
Name: 歩数, dtype: bool

In [5]:
df_selected = df[df["歩数"] >= 10000]
df_selected

            日付     歩数  摂取カロリー
2   2017-04-03  10238    1950
8   2017-04-09  12045    1950
12  2017-04-13  10287    1800
19  2017-04-20  15328    1800
20  2017-04-21  12849    1940

In [6]:
df_selected.shape

(5, 3)

In [7]:
df.query("歩数 >= 10000 and 摂取カロリー <= 1800")

            日付     歩数  摂取カロリー
12  2017-04-13  10287    1800
19  2017-04-20  15328    1800

In [8]:
df.dtypes

日付        object
歩数         int64
摂取カロリー     int64
dtype: object

In [9]:
df.loc[:,"date"] = df.loc[:,"日付"].apply(pd.to_datetime)

In [12]:
df.loc[:,"date"]

0    2017-04-01
1    2017-04-02
2    2017-04-03
3    2017-04-04
4    2017-04-05
5    2017-04-06
6    2017-04-07
7    2017-04-08
8    2017-04-09
9    2017-04-10
10   2017-04-11
11   2017-04-12
12   2017-04-13
13   2017-04-14
14   2017-04-15
15   2017-04-16
16   2017-04-17
17   2017-04-18
18   2017-04-19
19   2017-04-20
20   2017-04-21
21   2017-04-22
22   2017-04-23
23   2017-04-24
24   2017-04-25
25   2017-04-26
26   2017-04-27
27   2017-04-28
28   2017-04-29
29   2017-04-30
Name: date, dtype: datetime64[ns]

In [54]:
df = df.set_index("date")
df.head(6)

                    日付     歩数  摂取カロリー
date
2017-04-01  2017-04-01   5439    2500
2017-04-02  2017-04-02   2510    2300
2017-04-03  2017-04-03  10238    1950
2017-04-04  2017-04-04   8209    1850
2017-04-05  2017-04-05   9434    1930
2017-04-06  2017-04-06   7593    1800

In [58]:
df.sort_values(by="歩数").head()

                    日付    歩数  摂取カロリー
date
2017-04-02  2017-04-02  2510    2300
2017-04-23  2017-04-23  3890    1950
2017-04-22  2017-04-22  4029    2300
2017-04-30  2017-04-30  4093    1950
2017-04-08  2017-04-08  4873    2300

In [59]:
df.sort_values(by="歩数", ascending=False).head()

                    日付     歩数  摂取カロリー
date
2017-04-20  2017-04-20  15328    1800
2017-04-21  2017-04-21  12849    1940
2017-04-09  2017-04-09  12045    1950
2017-04-13  2017-04-13  10287    1800
2017-04-03  2017-04-03  10238    1950

In [60]:
df = df.drop("日付", axis=1)

In [61]:
df.tail()

              歩数  摂取カロリー
date
2017-04-26  7492    1850
2017-04-27  7203    1930
2017-04-28  7302    1850
2017-04-29  6033    2300
2017-04-30  4093    1950

In [65]:
df.loc[:,"歩数/カロリー"] = df.loc[:,"歩数"]/df.loc[:,"摂取カロリー"]
df.head()

               歩数  摂取カロリー   歩数/カロリー
date
2017-04-01   5439    2500  2.175600
2017-04-02   2510    2300  1.091304
2017-04-03  10238    1950  5.250256
2017-04-04   8209    1850  4.437297
2017-04-05   9434    1930  4.888083

In [66]:
def exercise_judge(ex):
    if ex <= 3.0:
        return "Low"
    elif 3.0 < ex <= 6.0:
        return "Mid"
    else:
        return "High"

In [67]:
df.loc[:,"運動指数"] = df.loc[:,"歩数/カロリー"].apply(exercise_judge)
df.head()

               歩数  摂取カロリー   歩数/カロリー 運動指数
date
2017-04-01   5439    2500  2.175600  Low
2017-04-02   2510    2300  1.091304  Low
2017-04-03  10238    1950  5.250256  Mid
2017-04-04   8209    1850  4.437297  Mid
2017-04-05   9434    1930  4.888083  Mid

In [68]:
df.to_pickle("data/df_201704health.pickle")

In [69]:
df_moved = pd.get_dummies(df.loc[:,"運動指数"], prefix="運動")
df_moved.head()

            運動_High  運動_Low  運動_Mid
date
2017-04-01        0       1       0
2017-04-02        0       1       0
2017-04-03        0       0       1
2017-04-04        0       0       1
2017-04-05        0       0       1

In [71]:
df_moved.to_pickle("data/df_201704moved.pickle")

In [72]:
dates = pd.date_range(start="2017-04-01",end="2017-04-30")
dates

DatetimeIndex(['2017-04-01', '2017-04-02', '2017-04-03', '2017-04-04',
               '2017-04-05', '2017-04-06', '2017-04-07', '2017-04-08',
               '2017-04-09', '2017-04-10', '2017-04-11', '2017-04-12',
               '2017-04-13', '2017-04-14', '2017-04-15', '2017-04-16',
               '2017-04-17', '2017-04-18', '2017-04-19', '2017-04-20',
               '2017-04-21', '2017-04-22', '2017-04-23', '2017-04-24',
               '2017-04-25', '2017-04-26', '2017-04-27', '2017-04-28',
               '2017-04-29', '2017-04-30'],
              dtype='datetime64[ns]', freq='D')

In [75]:
np.random.seed(123)
df = pd.DataFrame(np.random.randint(1,31,30), index=dates, columns=["乱数"])
df.head()

            乱数
2017-04-01  14
2017-04-02   3
2017-04-03  29
2017-04-04   3
2017-04-05   7

In [104]:
dates = pd.date_range(start="2017-01-01",periods=365)
dates

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06', '2017-01-07', '2017-01-08',
               '2017-01-09', '2017-01-10',
               ...
               '2017-12-22', '2017-12-23', '2017-12-24', '2017-12-25',
               '2017-12-26', '2017-12-27', '2017-12-28', '2017-12-29',
               '2017-12-30', '2017-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')

In [106]:
np.random.seed(123)
df = pd.DataFrame(np.random.randint(1,31,365), index=dates, columns=["乱数"])
df

            乱数
2017-01-01  14
2017-01-02   3
2017-01-03  29
2017-01-04   3
2017-01-05   7
...         ..
2017-12-27  22
2017-12-28   5
2017-12-29  22
2017-12-30   1
2017-12-31   8

[365 rows x 1 columns]

In [127]:
df.groupby(pd.Grouper(freq="M")).mean()

                   乱数
2017-01-31  13.774194
2017-02-28  13.428571
2017-03-31  15.612903
2017-04-30  15.533333
2017-05-31  15.322581
2017-06-30  14.300000
2017-07-31  15.258065
2017-08-31  16.129032
2017-09-30  18.433333
2017-10-31  14.580645
2017-11-30  12.633333
2017-12-31  17.483871

In [128]:
df.loc[:,"乱数"].resample("M").mean()

2017-01-31    13.774194
2017-02-28    13.428571
2017-03-31    15.612903
2017-04-30    15.533333
2017-05-31    15.322581
2017-06-30    14.300000
2017-07-31    15.258065
2017-08-31    16.129032
2017-09-30    18.433333
2017-10-31    14.580645
2017-11-30    12.633333
2017-12-31    17.483871
Freq: M, Name: 乱数, dtype: float64

In [129]:
pd.date_range(start="2017-01-01", end="2017-12-31",freq="W-SAT")

DatetimeIndex(['2017-01-07', '2017-01-14', '2017-01-21', '2017-01-28',
               '2017-02-04', '2017-02-11', '2017-02-18', '2017-02-25',
               '2017-03-04', '2017-03-11', '2017-03-18', '2017-03-25',
               '2017-04-01', '2017-04-08', '2017-04-15', '2017-04-22',
               '2017-04-29', '2017-05-06', '2017-05-13', '2017-05-20',
               '2017-05-27', '2017-06-03', '2017-06-10', '2017-06-17',
               '2017-06-24', '2017-07-01', '2017-07-08', '2017-07-15',
               '2017-07-22', '2017-07-29', '2017-08-05', '2017-08-12',
               '2017-08-19', '2017-08-26', '2017-09-02', '2017-09-09',
               '2017-09-16', '2017-09-23', '2017-09-30', '2017-10-07',
               '2017-10-14', '2017-10-21', '2017-10-28', '2017-11-04',
               '2017-11-11', '2017-11-18', '2017-11-25', '2017-12-02',
               '2017-12-09', '2017-12-16', '2017-12-23', '2017-12-30'],
              dtype='datetime64[ns]', freq='W-SAT')

In [132]:
df_year = pd.DataFrame(df.groupby(pd.Grouper(freq="W-SAT")).sum(),
                       columns=["乱数"])
df_year.head()

             乱数
2017-01-07   94
2017-01-14  109
2017-01-21   85
2017-01-28   93
2017-02-04   81