In [1]:
import pandas as pd
df = pd.read_csv("data/201704health.csv", encoding="utf-8")
df.head(6)

           日付     歩数  摂取カロリー
0  2017-04-01   5439    2500
1  2017-04-02   2510    2300
2  2017-04-03  10238    1950
3  2017-04-04   8209    1850
4  2017-04-05   9434    1930
5  2017-04-06   7593    1800

In [2]:
df = pd.read_excel("data/201704health.xlsx")
df.head(6)

           日付     歩数  摂取カロリー
0  2017-04-01   5439    2500
1  2017-04-02   2510    2300
2  2017-04-03  10238    1950
3  2017-04-04   8209    1850
4  2017-04-05   9434    1930
5  2017-04-06   7593    1800

In [3]:
url="https://ja.wikipedia.org/wiki/%E3%83%88%E3%83%83%E3%83%97%E3%83%AC%E3%83%99%E3%83%AB%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E4%B8%80%E8%A6%A7"
tables=pd.read_html(url)

In [4]:
len(tables)

41

In [12]:
df=tables[4]

In [13]:
df.to_csv("data/write_data.csv")

In [15]:
df.to_excel("data/write_data.xlsx")

In [16]:
df.to_pickle("data/write_df.pickle")

In [18]:
df=pd.read_pickle("data/write_df.pickle")